### ISSUE TITLE
报告几个问题

### ISSUE THREAD

**Issue by fatinghenji** [MeetWq/nonebot-plugin-shindan#1]
## 使用`nb plugin install nonebot_plugin_shindan`安装会报错
 改用```pip install nonebot_plugin_shindan```后可以正常安装
```python3
root@localhost:~/bot# nb plugin install nonebot_plugin_shindan                                                                                                                       
Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                                                      
    sys.exit(main())                                                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__                                                                                                 
    return self.main(*args, **kwargs)                                                                                                                                                
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main                                                                                                     
    rv = self.invoke(ctx)                                                                                                                                                            
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke                                                                                                  
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                          
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke                                                                                                  
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                          
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke                                                                                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                   
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke                                                                                                   
    return callback(*args, **kwargs)                                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/__init__.py", line 116, in install                                                                                             
    install_plugin(name, file, index)                                                                                                                                                
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers.py", line 292, in install_plugin                                                                                      
    plugins = _get_plugins()                                                                                                                                                         
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers.py", line 360, in _get_plugins                                                                                        
    return list(map(lambda x: Plugin(**x), plugins))                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers.py", line 360, in <lambda>                                                                                            
    return list(map(lambda x: Plugin(**x), plugins))                                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 406, in __init__                                                                                              
    raise validation_error                                                                                                                                                           
pydantic.error_wrappers.ValidationError: 3 validation errors for Plugin                                                                                                              
id                                                                                                                                                                                   
  field required (type=value_error.missing)                                                                                                                                          
link                                                                                                                                                                                 
  field required (type=value_error.missing)                                                                                                                                          
repo                                                                                                                                                                                 
  field required (type=value_error.missing)  
```
## 指令`占卜列表`、`添加占卜 id 指令`、`删除占卜 id`无法被正确处理
```python3
01-09 01:17:06 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
01-09 01:18:09 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 34245421 from 2909954314@[群:601022072] "占卜列表"
01-09 01:18:35 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -662163118 from 2909954314@[群:601022072] "人设生成 小Q"
01-09 01:18:35 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:18:40 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:19:06 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -1081738479 from 2909954314@[群:601022072] "异世界转生 吉田"
01-09 01:19:06 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:19:11 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:19:40 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 287121608 from 2909954314@[群:601022072] "占卜列表"
01-09 01:20:07 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 1419202699 from 2909954314@[群:601022072] "魔法人生 吉田"
01-09 01:20:07 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:20:14 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:20:41 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -307499308 from 2909954314@[群:1062364304] "魔法人生 云寒烟"
01-09 01:20:41 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:20:49 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:26:31 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 2053661276 from 2909954314@[群:601022072] "删除占卜 940824"
01-09 01:26:44 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -760102357 from 2909954314@[群:601022072] "魔法人生 吉田"
01-09 01:26:44 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:26:51 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:27:52 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -1736149238 from 2909954314@[群:601022072] "添加占卜 1088007 魔法人生2.0"
01-09 01:28:10 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message -1642787689 from 2909954314@[群:601022072] "魔法人生2.0 吉田"
01-09 01:28:10 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False>
01-09 01:28:18 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_shindan, type=message, priority=9, temp=False> running complete
01-09 01:28:44 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 1249182082 from 2909954314@[群:601022072] "添加占卜 1088007 magic人生2.0"
01-09 01:28:54 [SUCCESS] nonebot | CQHTTP 1026152696 | [message.group.normal]: Message 138055172 from 2909954314@[群:601022072] "magic人生2.0 吉田"
```
## 新增占卜名称若带有已存在的名称则不会被正常识别（存疑）
![image](https://user-images.githubusercontent.com/37131177/148654022-49010e35-4aa6-448c-8a6d-3fd1c48abe2c.png)
![HUUOCVB2{WQ$5V`68O@`T@3](https://user-images.githubusercontent.com/37131177/148654028-e2a70de8-a09f-4bc8-9dab-fad995731e86.png)

**Comment by MeetWq** [comment]
nb plugin install 装不上我也不知道是什么问题，建议去 [nb-cli](https://github.com/nonebot/nb-cli) 反馈

占卜列表、添加占卜和删除占卜 应该是指令开头的问题，如果你没有改过 nonebot 的 `COMMAND_START` 设置的话，这三个指令需要以 `/` 开头

第三个问题，我给指令列表加了个排序，现在如果“魔法人生2.0”和“魔法人生”同时存在的话会优先按照“魔法人生2.0”处理。
